<?php
/**
 * Video abilities — list, get, update and restore, over internal REST dispatch.
 *
 * Every callback here dispatches to a route the plugin already registers rather than calling
 * Videos_Controller directly. Dispatching runs the route's registered arg defaults, its sanitize
 * callbacks (the `fields` allowlist and `sanitize_ids_param` included) and its own permission
 * callback, so an ability inherits every existing guard and duplicates none of the pagination or
 * search logic.
 *
 * Deliberately not exposed: creating a video, permanent delete (`force=true`) and emptying the
 * trash. `vidshop/trash-video` is the reversible half and lives in its own provider.
 *
 * @package vidshop-for-woocommerce
 */

namespace VSFW\Abilities;

/**
 * Ability definitions for the videos library.
 */
class Videos_Abilities {

	/**
	 * Build the ability definitions.
	 *
	 * Returns a map of ability name => registration args. Registration itself stays in
	 * Abilities_Module so a failure is visible in one place.
	 *
	 * @param Abilities_Module $module Abilities module, source of the shared helpers.
	 * @return array Ability name => args array.
	 */
	public static function definitions( $module ) {
		return array(
			'vidshop/list-videos'   => array(
				'label'               => __( 'List VidShop videos', 'vidshop-for-woocommerce' ),
				'description'         => __( 'Lists shoppable videos from the VidShop library with pagination, search, status and origin filters, and returns the WooCommerce products attached to each video. Use it to answer which videos exist, which are still drafts, and which perform best.', 'vidshop-for-woocommerce' ),
				'category'            => Abilities_Module::CATEGORY,
				'input_schema'        => array(
					'type'                 => 'object',
					'properties'           => array(
						'page'     => array(
							'type'        => 'integer',
							'minimum'     => 1,
							'description' => __( 'Page of results to return, starting at 1. Defaults to 1. Increase it to walk through a library larger than one page.', 'vidshop-for-woocommerce' ),
						),
						'per_page' => array(
							'type'        => 'integer',
							'minimum'     => 1,
							'maximum'     => 100,
							'description' => __( 'How many videos to return per page, from 1 to 100. Defaults to 20. Keep it small when you only need a sample.', 'vidshop-for-woocommerce' ),
						),
						'search'   => array(
							'type'        => 'string',
							'description' => __( 'Free-text search over video titles. Omit it to list everything.', 'vidshop-for-woocommerce' ),
						),
						'status'   => array(
							'type'        => 'string',
							'enum'        => array( 'all', 'published', 'draft', 'trash' ),
							'description' => __( 'Filter by publication status: published for live videos, draft for unreviewed ones (AI-generated videos land here), trash for soft-deleted ones, all for every status except the trash.', 'vidshop-for-woocommerce' ),
						),
						'origin'   => array(
							'type'        => 'string',
							'enum'        => array( 'manual', 'wpcreatix_ai' ),
							'description' => __( 'Filter by how the video was created: manual for merchant uploads, wpcreatix_ai for videos generated by VidShop AI.', 'vidshop-for-woocommerce' ),
						),
						'orderby'  => array(
							'type'        => 'string',
							'enum'        => array( 'id', 'title', 'created_at', 'date', 'random', 'views' ),
							'description' => __( 'Field to sort by. Use views to rank by popularity, created_at or date for newest first, random for a shuffled sample.', 'vidshop-for-woocommerce' ),
						),
						'order'    => array(
							'type'        => 'string',
							'enum'        => array( 'asc', 'desc' ),
							'description' => __( 'Sort direction: asc for ascending, desc for descending.', 'vidshop-for-woocommerce' ),
						),
						'ids'      => array(
							'type'        => 'string',
							'description' => __( 'Comma-separated list of video IDs to fetch, for example "4,9,12". Use it to look up a known set in one call instead of paging.', 'vidshop-for-woocommerce' ),
						),
					),
					'additionalProperties' => false,
					'required'             => array(),
					'default'              => array(),
				),
				// No output_schema: the payload is controller-owned and carries per-video product
				// arrays, so declaring it would risk ability_invalid_output, and there is no escape
				// hatch without subclassing core's ability class, which this directory forbids.
				'execute_callback'    => static function ( $input = null ) use ( $module ) {
					return $module->dispatch(
						'GET',
						'/vsfw/v1/videos',
						$module->apply_defaults(
							$input,
							array(
								'page'     => 1,
								'per_page' => 20,
							)
						)
					);
				},
				'permission_callback' => $module->permission_callback( 'vidshop/list-videos' ),
				'meta'                => $module->meta(
					array(
						'readonly'    => true,
						'destructive' => false,
						'idempotent'  => true,
					)
				),
			),

			'vidshop/get-video'     => array(
				'label'               => __( 'Get a VidShop video', 'vidshop-for-woocommerce' ),
				'description'         => __( 'Returns one shoppable video with its full attached-product payloads: price, stock, attributes and variations. Read this before editing a video or reporting on what it sells.', 'vidshop-for-woocommerce' ),
				'category'            => Abilities_Module::CATEGORY,
				'input_schema'        => array(
					'type'                 => 'object',
					'properties'           => array(
						'id' => array(
							'type'        => 'integer',
							'minimum'     => 1,
							'description' => __( 'The VidShop video row ID, as returned by vidshop/list-videos. This is not a WordPress post ID and not the attachment ID of the video file.', 'vidshop-for-woocommerce' ),
						),
					),
					'additionalProperties' => false,
					'required'             => array( 'id' ),
				),
				// No output_schema: the product payloads (attributes, variations, stock) are shaped
				// by WooCommerce::prepare_product and are too wide to declare safely.
				'execute_callback'    => static function ( $input = null ) use ( $module ) {
					$input = is_array( $input ) ? $input : array();
					$id    = isset( $input['id'] ) ? (int) $input['id'] : 0;

					return $module->dispatch( 'GET', '/vsfw/v1/videos/' . $id );
				},
				'permission_callback' => $module->permission_callback( 'vidshop/get-video' ),
				'meta'                => $module->meta(
					array(
						'readonly'    => true,
						'destructive' => false,
						'idempotent'  => true,
					)
				),
			),

			'vidshop/update-video'  => array(
				'label'               => __( 'Update a VidShop video', 'vidshop-for-woocommerce' ),
				'description'         => __( 'Updates one shoppable video. This single ability covers renaming it, changing its poster frame, publishing or unpublishing it, and attaching WooCommerce products to it. Only the fields you send are changed; every field you omit is left exactly as it is.', 'vidshop-for-woocommerce' ),
				'category'            => Abilities_Module::CATEGORY,
				'input_schema'        => array(
					'type'                 => 'object',
					'properties'           => array(
						'id'           => array(
							'type'        => 'integer',
							'minimum'     => 1,
							'description' => __( 'The VidShop video row ID to update, as returned by vidshop/list-videos.', 'vidshop-for-woocommerce' ),
						),
						'title'        => array(
							'type'        => 'string',
							'description' => __( 'New title for the video, shown to shoppers in the storefront.', 'vidshop-for-woocommerce' ),
						),
						'thumbnail_id' => array(
							'type'        => 'integer',
							'description' => __( 'Attachment ID of an image in the Media Library to use as the poster frame.', 'vidshop-for-woocommerce' ),
						),
						'status'       => array(
							'type'        => 'string',
							'enum'        => array( 'published', 'draft' ),
							'description' => __( 'Publication status: published makes the video live in storefronts, draft hides it. AI-generated videos arrive as drafts, so this is how you approve one.', 'vidshop-for-woocommerce' ),
						),
						'settings'     => array(
							'type'                 => 'object',
							'additionalProperties' => true,
							'description'          => __( 'Per-video settings. The keys you send are merged into the stored settings, so keys you leave out keep their current values.', 'vidshop-for-woocommerce' ),
						),
						'products'     => array(
							'type'        => 'array',
							'items'       => array(
								'type' => 'integer',
							),
							'description' => __( 'WooCommerce product IDs to feature in this video. This is a full replace: any product not listed is detached.', 'vidshop-for-woocommerce' ),
						),
					),
					'additionalProperties' => false,
					'required'             => array( 'id' ),
				),
				// No output_schema: the response is the updated video with controller-owned product
				// payloads attached.
				'execute_callback'    => static function ( $input = null ) use ( $module ) {
					$input  = is_array( $input ) ? $input : array();
					$id     = isset( $input['id'] ) ? (int) $input['id'] : 0;
					$params = array();

					/*
					 * Send only the keys the caller actually set. The controller is partial-safe
					 * precisely because an absent key is left alone: `settings` is merged with the
					 * stored blob and `products` is only re-synced when the key is present. Sending
					 * a defaulted key would silently clear settings or detach every product.
					 */
					foreach ( array( 'title', 'thumbnail_id', 'status', 'settings', 'products' ) as $key ) {
						if ( array_key_exists( $key, $input ) ) {
							$params[ $key ] = $input[ $key ];
						}
					}

					return $module->dispatch( 'PUT', '/vsfw/v1/videos/' . $id, $params );
				},
				'permission_callback' => $module->permission_callback( 'vidshop/update-video' ),
				'meta'                => $module->meta(
					array(
						'readonly'    => false,
						'destructive' => false,
						'idempotent'  => false,
					)
				),
			),

			'vidshop/restore-video' => array(
				'label'               => __( 'Restore a trashed VidShop video', 'vidshop-for-woocommerce' ),
				'description'         => __( 'Restores a video from the trash and returns it to draft status, clearing the deletion stamp. This is the undo half of vidshop/trash-video. It fails if the video is not currently in the trash.', 'vidshop-for-woocommerce' ),
				'category'            => Abilities_Module::CATEGORY,
				'input_schema'        => array(
					'type'                 => 'object',
					'properties'           => array(
						'id' => array(
							'type'        => 'integer',
							'minimum'     => 1,
							'description' => __( 'The VidShop video row ID to restore. List trashed videos with vidshop/list-videos using status "trash".', 'vidshop-for-woocommerce' ),
						),
					),
					'additionalProperties' => false,
					'required'             => array( 'id' ),
				),
				// No output_schema: the response is the restored video row as the controller shapes it.
				'execute_callback'    => static function ( $input = null ) use ( $module ) {
					$input = is_array( $input ) ? $input : array();
					$id    = isset( $input['id'] ) ? (int) $input['id'] : 0;

					return $module->dispatch( 'POST', '/vsfw/v1/videos/' . $id . '/restore' );
				},
				'permission_callback' => $module->permission_callback( 'vidshop/restore-video' ),
				'meta'                => $module->meta(
					array(
						'readonly'    => false,
						'destructive' => false,
						'idempotent'  => false,
					)
				),
			),
		);
	}
}
